#! /bin/sh

# basic
alias c="clear"
alias ls="ls --color"
alias targz="tar -I pigz -cvf"
alias untargz="tar -I pigz -xvf"

# user
alias st="speedtest"
alias shut="shutdown now"
alias youtube-dl="yt-dlp"

# systemctl
# sudo
alias sck="sudo systemctl kill"
alias scq="sudo systemctl stop"
alias scs="sudo systemctl status"
alias sce="sudo systemctl enable"
alias scd="sudo systemctl disable"
alias scr="sudo systemctl restart"
alias sct="sudo systemctl start"
# user
alias scuk="systemctl kill --user"
alias scuq="systemctl stop --user"
alias scus="systemctl status --user"
alias scue="systemctl enable --user"
alias scud="systemctl disable --user"
alias scur="systemctl restart --user"
alias scut="systemctl start --user"

# yarn
alias ya="yarn add"
alias yad="yarn add -D"
alias yap="yarn add -P"
alias yin="yarn install"
alias yrm="yarn remove"
alias yd="yarn dev"
alias yl="yarn lint"
alias yb="yarn build"
alias ys="yarn start"
alias yt="yarn test"

# pnpm
alias pa="pnpm add"
alias pad="pnpm add -D"
alias pap="pnpm add -P"
alias pin="pnpm install"
alias prm="pnpm rm"
alias pd="pnpm dev"
alias pl="pnpm lint"
alias pb="pnpm build"
alias pst="pnpm start"
alias pup="pnpm up"

# docker
alias d="docker"
alias db="docker build"
alias dl="docker logs"
alias dps="docker ps"
alias dco="docker container"
alias dim="docker image"
alias dims="docker images"
alias dc="docker-compose"
alias dcl="docker-compose logs"
alias dcup="docker-compose up"
alias dcd="docker-compose down"
alias dx="docker buildx"
alias dxb="docker buildx build"

# tauri
alias ytd="yarn tauri dev"
alias ytb="yarn tauri build"
