#! /bin/sh

SKIP="--needed --noconfirm"

sl_install() {
  local target=sl/$1
  if [ ! -d $target ]; then
    git clone https://github.com/Choooks22/$1 $target
  fi
  sudo make -C $target clean install
}

dwm() {
  sl_install dwm
}

slstatus() {
  sl_install slstatus
}

yay_install() {
  if command -v yay &> /dev/null; then
    echo "yay already installed."
    exit
  fi

  git clone https://aur.archlinux.org/yay /tmp/yay
  cd /tmp/yay && makepkg -si
}

powerlevel10k() {
  if [ -d p10k ]; then
    echo "powerlevel10k already installed."
    exit
  fi

  git clone --depth=1 https://github.com/romkatv/powerlevel10k p10k
}

xorg() {
	sudo pacman -S $SKIP xorg-server xorg-xinit xorg-xrandr xorg-xinput
}

fonts() {
  sudo pacman -S $SKIP \
    noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra \
    ttf-jetbrains-mono ttf-nerd-fonts-symbols-common ttf-nerd-fonts-symbols-2048-em
}

audio() {
  local audio_pkgs="pipewire pipewire-pulse pipewire-media-session"
	sudo pacman -S $SKIP $audio_pkgs pipewire-jack alsa-utils
	systemctl enable --user --now $audio_pkgs
}

utils() {
  sudo pacman -S $SKIP zsh kitty unzip pigz rofi picom feh playerctl openssh gnome-keyring
}

lightdm() {
	yay -S $SKIP lightdm lightdm-mini-greeter
	sudo systemctl enable lightdm

  # Copy config
  sudo cp lightdm/* /etc/lightdm

  # Update user
	sudo sed -i "s/^user = CHANGE_ME/user = $USER/" /etc/lightdm/lightdm-mini-greeter.conf

  # Create dwm desktop entry
  sudo mkdir -p /usr/share/xsessions
  if [ ! -f /usr/share/xsessions/dwm.desktop &> /dev/null ]; then
    sudo tee /usr/share/xsessions/dwm.desktop &> /dev/null <<-EOF
	    [Desktop Entry]
	    Name=dwm
	    Comment=Dynamic Window Manager
	    Exec=$(which dwm)
	    Type=XSession
EOF
  fi
}

nvm_install() {
	if command nvm &> /dev/null; then
		echo "nvm already installed."
		exit
	fi

  mkdir $NVM_DIR
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | sh
}

nnn_install() {
  sudo pacman -S $SKIP nnn mpv tree lowdown bat ffmpeg ffmpegthumbnailer w3m
}

apps() {
  yay -S $SKIP firefox discord-canary-electron-bin vscodium-bin vscodium-bin-marketplace flameshot
  nvm_install
  nnn_install
}

amdgpu() {
  sudo pacman -S $SKIP xf86-video-amdgpu vulkan-radeon mesa libva-mesa-driver mesa-vdpau
}

"$@"
