#! /bin/sh

# Env Vars

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

export EDITOR=vim

export XDG_CONFIG_DIR=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache

find $XDG_CONFIG_DIR/autostart.d -type f -exec bash -c '"{}" &' \;
